### ISSUE TITLE
[BUG] Migrating Deployments from OCP 3.x to 4.x failed due to apiVersion mismatch 

### ISSUE THREAD

**Issue by stillalearner** [konveyor/crane#102]
**What version of crane are you running, and what are your clutsters+platform**
Description: Installed crane-operator and migrating a single nginx deployment from OCP 3.11
Source cluster -> OCP 3.11 gcp
Target cluster -> OCP 4.11 gcp

**What did you expect to happen?**
The deployment should be successfully migrated to the target cluster and the pods should be running.

**What actually happened?**
The PipelineRun failed at kubectl-apply-kustomize due to apiVersion mismatch in 4.x

**Logs:**
secret/deployer-token-v5vbb created
error: resource mapping not found for name: "attached-pvc" namespace: "attached-pvc" from "/workspace/kustomize": no matches for kind "Deployment" in version "extensions/v1beta1"
ensure CRDs are installed first

cc: @djzager

**Comment by jmontleon** [comment]
This might not be straight forward with every resource type, but given 3.11 is the only 3.x version supported anymore, and it supports deployments.apps/v1 I think we should be exporting deployments as such so that it can be reimported on any 3.11+ cluster.

It should be possible to get it from the api server as such:
```
$ oc get deployment.apps mariadb -o yaml
apiVersion: apps/v1
kind: Deployment
```
vs
```
$ oc get deployment mariadb -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
```

```

```
$ curl -k -L -H "Authorization: Bearer $TOKEN" https://openshift3-node.montleon.intra:8443/apis/apps/v1/namespaces/mediawiki/deployments/mariadb
{
  "kind": "Deployment",
  "apiVersion": "apps/v1",
...
```

**Comment by sseago** [comment]
Whatever we do with deployments should probably also be done for daemonsets and replicasets.
