### ISSUE TITLE
Plugin Manager only uses a relative path for the default plugins

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/crane#89]
We should have a common place where all the plugins live, that can be shared.

plugin-manager add ..... 

Should go to something like `~/.crane/plugins....`

**Comment by eriknelson** [comment]
@JaydipGabani has this already been done?

**Comment by jmontleon** [comment]
The current behavior works well for running in a container. Using a relatively path in relation to the WORKDIR means that regardless of what user the container runs as the plugin is where it needs to be. Otherwise we need to be concerned with whether crane-runner is running as root with $HOME as /root (running on a vanilla Kubernetes cluster) or setting a user for a random uid set by OpenShift, etc.

My two cents: it might be desirable to look through a few locations 
`/usr/share/crane/plugins` - might be useful if we ever create RPMS for crane and plugins
`~/.local/share/crane/plugins` - good for when a user runs crane plugin-manager add ...
`$PWD/plugins` - relative path good for running in a container.

**Comment by eriknelson** [comment]
@jmontleon maybe worth a quick scrum chat for a decision? I'm not sure we need a full blown enhancement on this one.

**Comment by jmontleon** [comment]
I'll add it to the list for Tuesday!
